import { useState, useRef } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home() {
  const inputRef = useRef();
  const { shortURL, setShortURL } = useState('');

  const handleSubmit = (e) => {
    e.preventDefault(); // prevents page reloading
    const url = inputRef.current.value; // get value from input
    //TODO: peticion al API

    fetch('/api/acortaUrl', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        },
        body: JSON.stringify({ url }),
    })
    .then(res => res.json())
    .then(data => { 
      setShortURL(data.shortURL);
    })
  };


  return (
    <div className={styles.container}>
      <Head>
        <title>Acortar URL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Acortar URL
        </h1>

        <p className={styles.description}>
          Acortar tus URL's aqui
        </p>

        <div className={styles.grid}>
          <form className={styles.card} onSubmit={handleSubmit}>
            <input ref={inputRef} type="'text" className={styles.input} placeholder={'Ingresa tu URL'} />
            <button className={styles.button}>Acortar</button>
            <span className={styles.input}>
              {shortURL}
            </span>
          </form>
        </div>
      </main>

    </div>
  )
}
